import { Property } from '@/interfaces/estate.interfaces';

export const properties: Property[] = [
  {
    id: 1,
    title: 'Modern Luxury Villa',
    price: '$1,250,000',
    location: '123 Palm Avenue, Beverly Hills, CA 90210',
    image: '/img/estate/properties/villa.jpg',
    description:
      'This stunning modern villa offers luxury living at its finest. Featuring an open floor plan, high ceilings, and floor-to-ceiling windows that flood the space with natural light. The gourmet kitchen includes top-of-the-line appliances, custom cabinetry, and a large center island. The primary suite is a true retreat with a spa-like bathroom and walk-in closet. Outside, enjoy the private pool, outdoor kitchen, and beautifully landscaped grounds. Located in a prestigious neighborhood with easy access to shopping, dining, and entertainment.',
    beds: 5,
    baths: 4,
    area: '4,500 sq ft',
    lotSize: '0.5 acres',
    yearBuilt: 2020,
    type: 'house',
    garage: '2-Car Attached',
    heating: 'Central',
    cooling: 'Central Air',
    images: [
      '/img/estate/properties/villa1.jpg',
      '/img/estate/properties/villa2.jpg',
      '/img/estate/properties/villa3.jpg',
      '/img/estate/properties/villa4.jpg',
    ],
    features: [
      'pool',
      'garden',
      'fireplace',
      'garage',
      'balcony',
      'smart home',
    ],
    agent: {
      name: 'Sarah Johnson',
      image: '/img/estate/w1.jpg',
      phone: '(310) 555-1234',
      email: 'sarah@proestate.com',
    },
    coordinates: {
      lat: 34.0736,
      lng: -118.4004,
    },
    has3DTour: true,
    isVerified: true,
    matchScore: 98,
    saved: true,
    category: 'compare',
  },
  {
    id: 2,
    title: 'Downtown Penthouse',
    price: '$850,000',
    location: '456 Skyline Drive, Manhattan, NY 10001',
    image: '/img/estate/properties/penthouse.jpg',
    description:
      "Experience urban luxury in this stunning downtown penthouse with panoramic city views. The spacious open-concept living area features floor-to-ceiling windows, high-end finishes, and a chef's kitchen with premium appliances. The primary bedroom offers a lavish en-suite bathroom and generous closet space. Building features include 24/7 concierge, fitness center, rooftop terrace, and private parking. Located in the heart of the city with easy access to top restaurants, shopping, and cultural attractions.",
    beds: 3,
    baths: 2,
    area: '2,200 sq ft',
    lotSize: 'N/A',
    yearBuilt: 2018,
    type: 'condo, apartment',
    garage: '1-Car (Valet)',
    heating: 'Central',
    cooling: 'Central Air',
    images: [
      '/img/estate/properties/penthouse1.jpg',
      '/img/estate/properties/penthouse2.jpg',
      '/img/estate/properties/penthouse3.jpg',
    ],
    features: [
      'city view',
      'concierge',
      'balcony',
      'gym',
      'garage',
      'fitness center',
    ],
    agent: {
      name: 'Michael Chen',
      image: '/img/estate/m1.jpg',
      phone: '(212) 555-6789',
      email: 'michael@proestate.com',
    },
    coordinates: {
      lat: 34.0522,
      lng: -118.2437,
    },
    has3DTour: true,
    isVerified: true,
    matchScore: 85,
  },
  {
    id: 3,
    title: 'Seaside Cottage',
    price: '$675,000',
    location: '789 Oceanview Drive, Malibu, CA 90265',
    image: '/img/estate/properties/cottage.jpg',
    description:
      'Charming seaside cottage with direct beach access and breathtaking ocean views. This cozy retreat features a bright and airy open living space, updated kitchen with quartz countertops, and a spacious deck perfect for sunset watching. The primary bedroom opens to a private patio with ocean breezes. Enjoy the sound of waves from multiple outdoor living spaces. Just steps from the sand, this property offers the ultimate beach lifestyle with modern comforts.',
    beds: 2,
    baths: 2,
    area: '1,800 sq ft',
    lotSize: '0.25 acres',
    yearBuilt: 2015,
    type: 'house, townhouse',
    garage: '1-Car Detached',
    heating: 'Central',
    cooling: 'Central Air',
    images: [
      '/img/estate/properties/cottage1.jpg',
      '/img/estate/properties/cottage2.jpg',
      '/img/estate/properties/cottage3.jpg',
    ],
    features: [
      'ocean view',
      'beach access',
      'deck',
      'garden',
      'fireplace',
      'garage',
    ],
    agent: {
      name: 'Emily Rodriguez',
      image: '/img/estate/w2.jpg',
      phone: '(310) 555-2468',
      email: 'emily@proestate.com',
    },
    coordinates: {
      lat: 34.0259,
      lng: -118.7798,
    },
    priceReduced: true,
    has3DTour: false,
    isVerified: true,
    matchScore: 90,
    saved: true,
    category: 'favorites',
  },
  {
    id: 4,
    title: 'Mountain View Retreat',
    price: '$920,000',
    location: '101 Alpine Way, Aspen, CO 81611',
    image: '/img/estate/properties/mountain.jpg',
    description:
      'Spectacular mountain retreat offering privacy and breathtaking views. This custom-built home features a great room with vaulted ceilings, massive stone fireplace, and walls of windows framing the mountain vistas. The gourmet kitchen includes professional-grade appliances and a large island. The primary suite features a spa-like bathroom and private balcony. Outdoor living spaces include multiple decks, hot tub, and fire pit. Located minutes from world-class skiing and hiking, this is the perfect year-round mountain getaway.',
    beds: 4,
    baths: 3,
    area: '3,200 sq ft',
    lotSize: '1.2 acres',
    yearBuilt: 2019,
    type: 'house',
    garage: '2-Car Attached',
    heating: 'Radiant Floor',
    cooling: 'None',
    images: [
      '/img/estate/properties/mountain1.jpg',
      '/img/estate/properties/mountain2.jpg',
    ],
    features: ['mountain view', 'garage', 'fireplace', 'pool', 'garden', 'gym'],
    agent: {
      name: 'David Wilson',
      image: '/img/estate/m2.jpg',
      phone: '(970) 555-1357',
      email: 'david@proestate.com',
    },
    coordinates: {
      lat: 34.1478,
      lng: -118.1445,
    },
    has3DTour: true,
    isVerified: true,
    matchScore: 79,
    saved: true,
    category: 'for_later',
  },
];
export const PropertyTypes = [
  'house',
  'apartment',
  'condo',
  'townhouse',
  'land',
];
export const featuresList = ['pool', 'garden', 'garage', 'gym', 'balcony'];
export const priceRanges = [
  { value: '', label: 'Any Price' },
  { value: '0-100000', label: 'Under $100,000' },
  { value: '100000-250000', label: '$100,000 - $250,000' },
  { value: '250000-500000', label: '$250,000 - $500,000' },
  { value: '500000-750000', label: '$500,000 - $750,000' },
  { value: '750000-1000000', label: '$750,000 - $1,000,000' },
  { value: '1000000+', label: '$1,000,000+' },
];
export const bedroomOptions = ['', '1', '2', '3', '4', '5'];
export const bathroomOptions = ['', '1', '2', '3', '4'];
